### PR TITLE
Fix headless contact icon

### PR DESCRIPTION
**Pull request by reality-exe**
Made icons show regardless if weather or not the Headless user is in a shown session or not

* Solves issue #29

### CODE REVIEW

**Comment by Nutcake** [comment]
Thanks for the PR! 

Are you sure this approach always works? I could have sworn there are cases when the API doesn't always return this information correctly which is why I went for this hacky solution in the first place, but it's been a while since I've looked into it.

Also I'd appreciate it if you could change the commit message to be imperative case (`Fix headless contact icon`).

**Comment by reality-exe** [comment]
So far yes, it seems to be working with the headless' I have added (5 in total).

And yeah sure I'll change the title though that's more accurate for grammar

**Comment by Nutcake** [comment]
Imperative should be used to follow long standing git conventions. I follow this convention for all my commit messages and prefer things to be consistent. Grammatically this isn't an issue, as instead of saying what a commit does, you are basically \*telling\* the commit what it _should_ do.

For adjusting the message, I don't mean the title on the PR, I mean the actual commit message itself. 
You can change this by editing your local commit with the `--amend` option and then force-pushing to this branch.

**Comment by reality-exe** [comment]
Man im using the github desktop client i dunno how to do dat

**Pull request closed without merging**
